import { Experience, Registration, BoardingPass, WaitlistEntry, AppNotification, Announcement } from '../src/types';

export const allInitialExperiences: Experience[] = [
  {
    id: 'exp_siemens_01',
    title: 'Siemens Smart Infrastructure & Industrial IoT Center Visit',
    organization: 'Siemens Technology and Services',
    organizationDescription: 'Global industrial engineering and automation powerhouse driving digital transformation and smart energy grids across India.',
    organizationIndustry: 'Industrial Automation & IoT',
    organizationWebsite: 'https://www.siemens.com/in/en.html',
    organizationLogo: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=120&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=800&auto=format&fit=crop&q=80',
    experienceType: 'Industrial Visits',
    shortDescription: 'Hands-on exploration of Industry 4.0 automation architectures, digital twin simulations, and smart grid automation pipelines.',
    detailedDescription: 'Students will spend a full day at the state-of-the-art Siemens R&D Innovation Campus. The visit covers live programmable logic controller (PLC) demonstration labs, telemetry ingestion pipelines, predictive maintenance sensor grids, and an exclusive technical briefing with principal automation architects.',
    date: '2026-09-12',
    location: 'Siemens Campus, Kalwa Industrial Estate, Thane',
    address: 'Thane Belapur Road, Airoli / Kalwa Industrial Area, Thane, Maharashtra 400601',
    contribution: 450,
    capacity: 35,
    waitlistEnabled: true,
    waitlistCapacity: 15,
    registrationOpen: '2026-08-01T00:00:00Z',
    registrationDeadline: '2026-09-05T23:59:59Z',
    status: 'PUBLISHED',
    createdBy: 'usr_faculty_1',
    primaryFacultyId: 'usr_faculty_1',
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-08-10T12:00:00Z',
    eligibility: {
      allowedBranches: ['Computer Science & Engineering', 'Electronics & Communication Engineering', 'Information Technology', 'Electrical & Electronics Engineering'],
      allowedYears: [3, 4],
      allowedSemesters: [5, 6, 7, 8],
      allowedDivisions: ['A', 'B', 'C'],
      minCgpa: 7.5,
      additionalRules: 'Students must have completed or be currently enrolled in Computer Networks, Embedded Systems, or Industrial Automation.',
    },
    whatYouWillLearn: [
      'End-to-end industrial IoT telemetry pipelines and edge computing deployments',
      'Digital Twin simulation setups for factory robotics and power distribution',
      'Cybersecurity protocols for SCADA and PLC control networks',
      'Direct career pathways and internship opportunities at Siemens R&D',
    ],
    learningObjectives: [
      'Analyze modern cyber-physical system architectures in manufacturing',
      'Evaluate real-time telemetry ingestion using OPC-UA and MQTT protocols',
      'Understand zero-trust security postures within operational technology (OT)',
    ],
    experienceHighlights: [
      { icon: 'Factory', title: 'Smart Factory Testbed', description: 'Walkthrough of operational Industry 4.0 smart assembly lines.' },
      { icon: 'Cpu', title: 'Live PLC & SCADA Rig', description: 'Interactive demo of edge telemetry and real-time sensor analytics.' },
      { icon: 'Users', title: 'Lead Architect Keynote', description: 'Direct Q&A session with Siemens principal IoT engineering leaders.' },
      { icon: 'Shield', title: 'Industrial Safety Briefing', description: 'Certified factory-floor electrical and equipment safety training.' },
    ],
    whyAttend: [
      'Exposure to Tier-1 industrial automation hardware rarely accessible in college laboratories',
      'Understand practical application of Distributed Systems, Edge Computing, and MQTT messaging',
      'Exclusive interaction with recruitment managers for 2027 graduate engineer trainee roles',
      'Official Certificate of Industrial Exposure issued jointly by VIT and Siemens Technology',
    ],
    safetyInfo: {
      dressCode: 'Formal or semi-formal academic attire. Full-length trousers and sturdy closed leather/canvas shoes are strictly mandatory.',
      requiredGear: 'Safety helmets and anti-static ESD coats will be provided on site at the visitor briefing area.',
      importantRules: [
        'Strictly no photography or video recording in the prototype lab zones',
        'Remain with your assigned student cohort and faculty coordinator at all times',
        'Mobile phones must be set to silent throughout technical demonstrations',
      ],
    },
    companyInfo: {
      website: 'https://www.siemens.com/in/en.html',
      about: 'Siemens is a technology company focused on industry, infrastructure, transport, and healthcare. From more resource-efficient factories and resilient supply chains to smarter grids, Siemens creates technology with purpose.',
      employees: '320,000+ Globally (30,000+ in India)',
      headquarters: 'Munich, Germany / Regional HQ: Mumbai & Bengaluru',
    },
    itinerary: [
      { id: 'it_1', time: '07:30 AM', activity: 'Assembly & Verification', description: 'Report at VIT Main Gate Bus Bay #3 for identity card and boarding pass QR verification.', order: 1 },
      { id: 'it_2', time: '08:00 AM', activity: 'Campus Departure', description: 'University AC deluxe transit coach departs promptly for Kalwa Campus.', order: 2 },
      { id: 'it_3', time: '09:45 AM', activity: 'Arrival & Welcome Keynote', description: 'Visitor badge distribution and opening keynote on Digital Twins by Siemens VP of Engineering.', order: 3 },
      { id: 'it_4', time: '11:00 AM', activity: 'Live Lab Tour: Industry 4.0 Testbed', description: 'Demonstration of smart robotics, automated optical inspection, and sorting rigs.', order: 4 },
      { id: 'it_5', time: '01:00 PM', activity: 'Executive Networking Lunch', description: 'Complimentary lunch hosted at Siemens Executive Dining Facility.', order: 5 },
      { id: 'it_6', time: '02:00 PM', activity: 'Technical Breakout & Case Study', description: 'Hands-on telemetry latency troubleshooting and predictive maintenance architecture session.', order: 6 },
      { id: 'it_7', time: '04:30 PM', activity: 'Q&A & Departure', description: 'Feedback collection, group photography, and departure back to VIT Campus.', order: 7 },
      { id: 'it_8', time: '06:30 PM', activity: 'Campus Arrival', description: 'Safe arrival back at Vidyalankar Institute of Technology Main Gate.', order: 8 },
    ],
    travelInfo: {
      reportingTime: '07:30 AM',
      reportingLocation: 'VIT Main Gate — Bus Bay #3',
      departureTime: '08:00 AM',
      transport: 'University AC Deluxe Bus (Vehicle No: MH-01-VIT-401)',
      expectedArrival: '09:45 AM',
      returnDeparture: '04:30 PM',
      campusArrival: '06:30 PM',
    },
    requirements: [
      'Physical VIT Student Identity Card (Mandatory for entry gate clearance)',
      'Digital or printed VIT Industrial Exposure Boarding Pass with verified QR code',
      'Formal or semi-formal academic dress code with sturdy closed footwear',
      'Technical notebook and pen for session observations',
    ],
    rules: [
      'Strictly no photography or unauthorized recording in the Siemens R&D testbed zones',
      'Students must stay with the assigned faculty coordinator throughout the tour',
      'Safety gear (provided on site) must be worn in the active robotics bay at all times',
      'Punctuality is strictly enforced; buses will depart at scheduled times',
    ],
  },

  {
    id: 'exp_tcs_02',
    title: 'TCS Innovation Labs — Applied AI & Cloud Architecture Tour',
    organization: 'Tata Consultancy Services',
    organizationDescription: 'Global IT consulting, digital engineering, and enterprise AI transformation leader headquartered in Mumbai.',
    organizationIndustry: 'Cloud Computing & Artificial Intelligence',
    organizationWebsite: 'https://www.tcs.com',
    organizationLogo: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=120&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    experienceType: 'Technical Tours',
    shortDescription: 'Deep dive into large language model orchestration, enterprise multi-cloud setups, and autonomous testing systems.',
    detailedDescription: 'TCS Innovation Labs hosts an immersive technical tour highlighting enterprise AI deployment frameworks, high-throughput microservice architectures, and modern cloud security operations centers.',
    date: '2026-09-24',
    location: 'TCS Olympus Centre, Hiranandani Estate, Thane West, Mumbai',
    address: 'Rodas Enclave, Park Road, Hiranandani Estate, Thane West, Mumbai, Maharashtra 400607',
    contribution: 350,
    capacity: 40,
    waitlistEnabled: true,
    waitlistCapacity: 20,
    registrationOpen: '2026-08-05T00:00:00Z',
    registrationDeadline: '2026-09-18T23:59:59Z',
    status: 'PUBLISHED',
    createdBy: 'usr_faculty_1',
    primaryFacultyId: 'usr_faculty_1',
    createdAt: '2026-08-05T11:00:00Z',
    updatedAt: '2026-08-12T14:00:00Z',
    eligibility: {
      allowedBranches: ['Computer Science & Engineering', 'Information Technology', 'Electronics & Communication Engineering'],
      allowedYears: [2, 3, 4],
      allowedSemesters: [4, 5, 6, 7, 8],
      allowedDivisions: ['A', 'B', 'C', 'D'],
      minCgpa: 7.0,
      additionalRules: 'Open to students interested in cloud-native microservices, AI systems, and modern software engineering.',
    },
    whatYouWillLearn: [
      'Enterprise LLM evaluation, fine-tuning pipelines, and retrieval-augmented generation (RAG)',
      'Multi-cloud Kubernetes cluster orchestration and observability telemetry',
      'Zero-trust cloud network security monitoring and automated incident remediation',
      'Overview of TCS Research internships and TCS CodeVita pathways',
    ],
    learningObjectives: [
      'Understand enterprise AI lifecycle from dataset curation to inference serving',
      'Analyze cloud deployment patterns using Infrastructure as Code (Terraform & GitOps)',
      'Evaluate reliability engineering practices and chaos testing methodologies',
    ],
    experienceHighlights: [
      { icon: 'Cpu', title: 'AI Research Showcase', description: 'Interactive demo of in-house enterprise generative AI models and agents.' },
      { icon: 'Server', title: 'Cloud Command Center', description: 'Walkthrough of 24/7 global cloud telemetry and resilience monitors.' },
      { icon: 'Users', title: 'Tech Career Breakout', description: 'Discussion on R&D fellowship programs and career trajectories in TCS Research.' },
      { icon: 'Award', title: 'Code Challenge Spotlight', description: 'Tips and architectural problem breakdowns from TCS CodeVita judges.' },
    ],
    whyAttend: [
      'Experience how mission-critical software powering Fortune 500 banks and airlines is engineered',
      'Gain practical insights into AI agent deployment, security guardrails, and vector databases',
      'Direct interaction with Principal Researchers and Chief Architects',
    ],
    safetyInfo: {
      dressCode: 'Smart casual or business formal attire. Clean collared shirts and closed shoes.',
      requiredGear: 'Visitor smart cards will be issued upon arrival at the security reception.',
      importantRules: [
        'Access strictly confined to TCS Innovation Labs and Visitor Conference Suites',
        'Non-disclosure agreement (NDA) rules apply to prototype demo screens',
      ],
    },
    companyInfo: {
      website: 'https://www.tcs.com',
      about: 'Tata Consultancy Services is an IT services, consulting and business solutions organization that has been partnering with many of the worlds largest businesses in their transformation journeys for over 55 years.',
      employees: '600,000+ Globally',
      headquarters: 'Mumbai, Maharashtra, India',
    },
    itinerary: [
      { id: 'it_tcs1', time: '08:15 AM', activity: 'Campus Reporting', description: 'Assemble at VIT Central Plaza for attendance verification.', order: 1 },
      { id: 'it_tcs2', time: '08:45 AM', activity: 'Transit Departure', description: 'Air-conditioned bus leaves for TCS Olympus Campus.', order: 2 },
      { id: 'it_tcs3', time: '10:15 AM', activity: 'Security Badging & Welcome', description: 'Reception check-in and briefing by Head of Academic Relations.', order: 3 },
      { id: 'it_tcs4', time: '11:00 AM', activity: 'Applied AI & RAG Deep Dive', description: 'Keynote and technical demos on enterprise GenAI workflows.', order: 4 },
      { id: 'it_tcs5', time: '01:00 PM', activity: 'Networking Buffet Lunch', description: 'Buffet lunch hosted at Olympus Food Court.', order: 5 },
      { id: 'it_tcs6', time: '02:00 PM', activity: 'Cloud Security Center Tour', description: 'Observability architectures, Kubernetes clusters, and zero-trust demo.', order: 6 },
      { id: 'it_tcs7', time: '03:45 PM', activity: 'Campus Career & Internship Q&A', description: 'Open forum on TCS Research Fellowships and hiring patterns.', order: 7 },
      { id: 'it_tcs8', time: '05:00 PM', activity: 'Return Transit', description: 'Coach leaves for VIT Campus; estimated arrival by 06:30 PM.', order: 8 },
    ],
    travelInfo: {
      reportingTime: '08:15 AM',
      reportingLocation: 'VIT Central Plaza — Bus Bay #1',
      departureTime: '08:45 AM',
      transport: 'University AC Transit Coach (Vehicle No: MH-01-VIT-202)',
      expectedArrival: '10:15 AM',
      returnDeparture: '05:00 PM',
      campusArrival: '06:30 PM',
    },
    requirements: [
      'Physical VIT Student ID Card (Mandatory)',
      'Digital Boarding Pass QR Code',
      'Smart casual or business formal collared attire',
      'Laptop optional for tech notes',
    ],
    rules: [
      'Respect confidentiality guidelines on unreleased AI tools',
      'No video recording in the secure network operations center',
    ],
  },

  {
    id: 'exp_tatamotors_03',
    title: 'Tata Motors EV Assembly & Robotic Body Shop Plant Tour',
    organization: 'Tata Motors Limited',
    organizationDescription: 'Indias leading automobile manufacturer pioneering electric mobility, advanced battery powertrains, and automated robotic manufacturing.',
    organizationIndustry: 'Automobile & Electric Vehicles',
    organizationWebsite: 'https://www.tatamotors.com',
    organizationLogo: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=120&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&auto=format&fit=crop&q=80',
    experienceType: 'Industrial Visits',
    shortDescription: 'Comprehensive walkthrough of robotic spot-welding lines, EV battery pack integration, and automated quality inspection.',
    detailedDescription: 'Witness high-speed KUKA and FANUC robotic arms weld chassis, integrate high-voltage EV battery packs, and perform automated laser tolerance inspections at one of Indias most advanced automotive plants.',
    date: '2026-08-31',
    location: 'Tata Motors Manufacturing Plant, Pimpri Industrial Corridor, Pune',
    address: 'Pimpri Industrial Corridor, Sector 10, Pune, Maharashtra 411018',
    contribution: 500,
    capacity: 30,
    waitlistEnabled: true,
    waitlistCapacity: 15,
    registrationOpen: '2026-08-10T00:00:00Z',
    registrationDeadline: '2026-09-25T23:59:59Z',
    status: 'PUBLISHED',
    createdBy: 'usr_faculty_2',
    primaryFacultyId: 'usr_faculty_2',
    createdAt: '2026-08-10T09:00:00Z',
    updatedAt: '2026-08-14T10:00:00Z',
    eligibility: {
      allowedBranches: ['Mechanical Engineering', 'Electronics & Communication Engineering', 'Electrical & Electronics Engineering', 'Computer Science & Engineering'],
      allowedYears: [2, 3, 4],
      allowedSemesters: [3, 4, 5, 6, 7, 8],
      allowedDivisions: ['A', 'B', 'C'],
      minCgpa: 6.8,
    },
    whatYouWillLearn: [
      'High-voltage EV battery pack design, thermal management, and BMS integration',
      'Automated robotic spot welding, laser trimming, and chassis assembly algorithms',
      'Quality 4.0 machine vision systems for sub-millimeter gap inspection',
    ],
    learningObjectives: [
      'Understand mechatronics workflows in modern automobile assembly lines',
      'Analyze power electronics and battery safety standards (AIS-038 & AIS-156)',
    ],
    experienceHighlights: [
      { icon: 'Factory', title: 'Robotic Body-in-White (BIW)', description: 'Over 120 synchronized industrial robots executing precision spot welds.' },
      { icon: 'BatteryCharging', title: 'EV Powertrain Integration', description: 'Step-by-step assembly of electric motor and battery packs.' },
      { icon: 'Gauge', title: 'Dyno Testing & Quality', description: 'Dynamometer testing, water ingress tests, and electronic ECU diagnostic scans.' },
      { icon: 'Users', title: 'Plant Chief Engineer Talk', description: 'Direct interaction on EV design trends and sustainability targets.' },
    ],
    whyAttend: [
      'First-hand observation of large-scale robotic automation in automotive manufacturing',
      'Direct relevance for mechanical, electronics, and automotive engineering subjects',
      'Exposure to India’s electric vehicle transition roadmap',
    ],
    safetyInfo: {
      dressCode: '100% cotton trousers and full sleeve shirts. Heavy leather shoes with thick soles required.',
      requiredGear: 'Safety helmets, high-visibility neon vests, and protective eyewear provided at the plant gate.',
      importantRules: [
        'Do not step outside designated yellow pedestrian walkways on the shop floor',
        'Never touch robotic fixtures or conveyor components',
      ],
    },
    companyInfo: {
      website: 'https://www.tatamotors.com',
      about: 'Tata Motors Limited is an Indian multinational automotive manufacturing company, producing passenger cars, trucks, vans, coaches, and electric vehicles.',
      employees: '75,000+ Globally',
      headquarters: 'Mumbai, Maharashtra, India',
    },
    itinerary: [
      { id: 'it_tm1', time: '06:00 AM', activity: 'Early Campus Departure', description: 'Assemble at VIT Main Gate; highway transit coach leaves for Pune.', order: 1 },
      { id: 'it_tm2', time: '09:30 AM', activity: 'Plant Arrival & Safety Induction', description: 'Mandatory 30-minute shop-floor safety protocol video and PPE issuance.', order: 2 },
      { id: 'it_tm3', time: '10:15 AM', activity: 'Body Shop & Robotic BIW Walkthrough', description: 'Witness automated spot-welding and structural frame alignment.', order: 3 },
      { id: 'it_tm4', time: '12:30 PM', activity: 'EV Battery & Powertrain Line', description: 'Clean assembly room observation for EV battery packs and wiring harnesses.', order: 4 },
      { id: 'it_tm5', time: '01:30 PM', activity: 'Lunch at Tata Motors Guest House', description: 'Complimentary lunch and refreshment break.', order: 5 },
      { id: 'it_tm6', time: '02:30 PM', activity: 'Final Trim, Chassis & ECU Testing', description: 'End-of-line dyno run and ECU calibration diagnostics.', order: 6 },
      { id: 'it_tm7', time: '03:45 PM', activity: 'Interactive Session with EV Engineers', description: 'Q&A on battery cell chemistry and motor control algorithms.', order: 7 },
      { id: 'it_tm8', time: '04:45 PM', activity: 'Return Transit', description: 'Departure back to Mumbai; arrival at VIT Campus around 08:30 PM.', order: 8 },
    ],
    travelInfo: {
      reportingTime: '05:45 AM',
      reportingLocation: 'VIT Main Gate — Bus Bay #2',
      departureTime: '06:00 AM',
      transport: 'University Inter-City AC Bus (Vehicle No: MH-01-VIT-909)',
      expectedArrival: '09:30 AM',
      returnDeparture: '04:45 PM',
      campusArrival: '08:30 PM',
    },
    requirements: ['Physical VIT ID Card', 'Boarding Pass QR', 'Closed heavy leather footwear', 'Safety waiver signed'],
    rules: ['Stay on marked pedestrian pathways', 'Strictly no photography on shop floor'],
  },

  {
    id: 'exp_reliance_04',
    title: 'Reliance Jio 5G Core & Green Energy Data Center Tour',
    organization: 'Reliance Industries & Jio Platforms',
    organizationDescription: 'Indias largest private enterprise operating Tier-4 hyper-scale green data centers, 5G standalone core networks, and renewable energy grids.',
    organizationIndustry: 'Telecommunications & Data Centers',
    organizationWebsite: 'https://www.ril.com',
    organizationLogo: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=120&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80',
    experienceType: 'Technical Tours',
    shortDescription: 'Exploration of cloud-native 5G standalone cores, optical submarine cable landing interfaces, and liquid-cooled data racks.',
    detailedDescription: 'Visit Reliance Corporate Park (RCP) in Navi Mumbai to inspect 5G core network packet brokers, optical fiber DWDM switches, and AI supercomputing infrastructure powered by green solar grids.',
    date: '2026-10-14',
    location: 'Reliance Corporate Park (RCP), Ghansoli, Navi Mumbai',
    address: 'Thane-Belapur Road, MIDC Industrial Area, Ghansoli, Navi Mumbai, Maharashtra 400701',
    contribution: 0,
    capacity: 45,
    waitlistEnabled: true,
    waitlistCapacity: 20,
    registrationOpen: '2026-08-15T00:00:00Z',
    registrationDeadline: '2026-10-05T23:59:59Z',
    status: 'PUBLISHED',
    createdBy: 'usr_faculty_1',
    primaryFacultyId: 'usr_faculty_1',
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-16T12:00:00Z',
    eligibility: {
      allowedBranches: ['Computer Science & Engineering', 'Information Technology', 'Electronics & Communication Engineering', 'Electrical & Electronics Engineering'],
      allowedYears: [3, 4],
      allowedSemesters: [5, 6, 7, 8],
      allowedDivisions: ['A', 'B', 'C', 'D'],
      minCgpa: 7.2,
    },
    whatYouWillLearn: [
      '5G Standalone (SA) core network slicing and Open RAN architectures',
      'Hyper-scale data center thermal dissipation and liquid cooling systems',
      'Optical DWDM transmission and high-availability submarine cable routing',
    ],
    learningObjectives: [
      'Analyze network function virtualization (NFV) and Software Defined Networking (SDN)',
      'Evaluate energy efficiency metrics (PUE) in green cloud computing facilities',
    ],
    experienceHighlights: [
      { icon: 'Wifi', title: '5G Core Network Lab', description: 'Live demonstration of network slicing with ultra-low latency guarantees.' },
      { icon: 'Server', title: 'Tier-4 Data Hall Preview', description: 'Observation of high-density AI compute server racks with precision cooling.' },
      { icon: 'Zap', title: 'Renewable Power Substation', description: 'Tour of dedicated clean energy and battery backup systems powering the campus.' },
    ],
    whyAttend: [
      '100% funded industrial exposure visit with no fee contribution required',
      'Direct exposure to the backbone network connecting over 450 million active users',
      'Interactive networking with senior Jio Platforms network architects',
    ],
    safetyInfo: {
      dressCode: 'Formal university attire with ID badge worn prominently.',
      requiredGear: 'Anti-static shoe covers for data hall viewing corridors.',
      importantRules: ['Biometric security protocols in effect', 'Strictly no magnetic items in server galleries'],
    },
    companyInfo: {
      website: 'https://www.ril.com',
      about: 'Reliance Industries Limited is an Indian multinational conglomerate headquartered in Mumbai, with diverse businesses in telecom, retail, energy, and digital services.',
      employees: '350,000+ Across India',
      headquarters: 'Mumbai, Maharashtra, India',
    },
    itinerary: [
      { id: 'it_ril1', time: '08:00 AM', activity: 'VIT Gate Assembly', description: 'Check-in and board University transit bus.', order: 1 },
      { id: 'it_ril2', time: '09:15 AM', activity: 'RCP Campus Arrival', description: 'Security clearance and orientation at Jio Central Auditorium.', order: 2 },
      { id: 'it_ril3', time: '10:00 AM', activity: '5G Core & Open RAN Architecture Session', description: 'Technical walkthrough of network function virtualization.', order: 3 },
      { id: 'it_ril4', time: '12:00 PM', activity: 'Hyper-Scale Data Center Viewing Gallery', description: 'Guided observation of server racks, liquid cooling, and PUE monitors.', order: 4 },
      { id: 'it_ril5', time: '01:15 PM', activity: 'Lunch at RCP Dining Hall', description: 'Complimentary executive meal.', order: 5 },
      { id: 'it_ril6', time: '02:15 PM', activity: 'Optical Backbone & Cloud Operations', description: 'Deep dive into national fiber DWDM infrastructure.', order: 6 },
      { id: 'it_ril7', time: '03:45 PM', activity: 'Q&A & Career Guidance', description: 'Discussion on graduate engineering roles at Jio Platforms.', order: 7 },
      { id: 'it_ril8', time: '05:00 PM', activity: 'Departure to Campus', description: 'Return to VIT Mumbai Campus by 06:15 PM.', order: 8 },
    ],
    travelInfo: {
      reportingTime: '08:00 AM',
      reportingLocation: 'VIT Main Gate — Bus Bay #1',
      departureTime: '08:30 AM',
      transport: 'University AC Transit Bus (Vehicle No: MH-01-VIT-105)',
      expectedArrival: '09:15 AM',
      returnDeparture: '05:00 PM',
      campusArrival: '06:15 PM',
    },
    requirements: ['VIT Student ID Card', 'Valid Govt ID proof (Aadhaar / PAN)', 'Boarding Pass QR'],
    rules: ['Follow escort protocols in data center security zone'],
  },

  {
    id: 'exp_lt_05',
    title: 'Larsen & Toubro Heavy Engineering & Advanced Robotics Facility',
    organization: 'Larsen & Toubro Limited',
    organizationDescription: 'Premier Indian multinational conglomerate in technology, engineering, construction, and high-precision manufacturing.',
    organizationIndustry: 'Heavy Engineering & Advanced Robotics',
    organizationWebsite: 'https://www.larsentoubro.com',
    organizationLogo: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=120&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=800&auto=format&fit=crop&q=80',
    experienceType: 'Industrial Visits',
    shortDescription: 'Observing heavy fabrication, CNC multi-axis machining, robotic submerged arc welding, and non-destructive testing.',
    detailedDescription: 'L&T Powai Knowledge City hosts an educational visit through high-precision manufacturing bays, aerospace pressure vessel fabrication, and advanced non-destructive ultrasonic testing labs.',
    date: '2026-10-20',
    location: 'L&T Powai Knowledge City, Saki Vihar Road, Powai, Mumbai',
    address: 'Gate No. 1, Saki Vihar Road, Powai, Mumbai, Maharashtra 400072',
    contribution: 400,
    capacity: 30,
    waitlistEnabled: true,
    waitlistCapacity: 15,
    registrationOpen: '2026-08-20T00:00:00Z',
    registrationDeadline: '2026-10-12T23:59:59Z',
    status: 'PUBLISHED',
    createdBy: 'usr_faculty_2',
    primaryFacultyId: 'usr_faculty_2',
    createdAt: '2026-08-20T09:30:00Z',
    updatedAt: '2026-08-22T11:00:00Z',
    eligibility: {
      allowedBranches: ['Mechanical Engineering', 'Electronics & Communication Engineering', 'Civil Engineering', 'Electrical & Electronics Engineering'],
      allowedYears: [2, 3, 4],
      allowedSemesters: [4, 5, 6, 7, 8],
      allowedDivisions: ['A', 'B'],
      minCgpa: 7.0,
    },
    whatYouWillLearn: [
      'Multi-axis CNC milling, turning, and EDM machining of exotic alloys',
      'Automated robotic submerged arc welding (SAW) and orbital welding procedures',
      'Ultrasonic, radiography, and magnetic particle non-destructive testing (NDT)',
    ],
    learningObjectives: [
      'Analyze ASME code compliance and heavy fabrication quality assurance',
      'Understand materials science applications in aerospace and nuclear hardware',
    ],
    experienceHighlights: [
      { icon: 'Factory', title: 'Heavy Fabrication Bay', description: 'Inspection of massive reactor pressure vessels and turbine casings.' },
      { icon: 'Layers', title: '5-Axis CNC Precision Suite', description: 'Demonstration of sub-micron tolerance metal carving.' },
      { icon: 'ShieldCheck', title: 'NDT Laboratory', description: 'Live ultrasonic flaw detection and industrial radiography demo.' },
    ],
    whyAttend: [
      'Located within central Mumbai for convenient transit',
      'Invaluable practical grounding for design of machine elements and manufacturing tech',
      'Direct interactions with senior L&T project engineers',
    ],
    safetyInfo: {
      dressCode: 'Heavy trousers and collared shirts. No loose jewelry or scarves allowed.',
      requiredGear: 'Hard hats, safety glasses, and ear plugs provided on site.',
      importantRules: ['Stay within visitor demarcations inside heavy crane operating bays'],
    },
    companyInfo: {
      website: 'https://www.larsentoubro.com',
      about: 'Larsen & Toubro is an Indian multinational conglomerate engaged in EPC projects, hi-tech manufacturing and services with operations worldwide.',
      employees: '50,000+ Core Workforce',
      headquarters: 'Mumbai, Maharashtra, India',
    },
    itinerary: [
      { id: 'it_lt1', time: '08:00 AM', activity: 'Reporting at VIT Gate', description: 'Bus boarding and attendance roll call.', order: 1 },
      { id: 'it_lt2', time: '09:15 AM', activity: 'L&T Powai Gate 1 Check-in', description: 'Security gate passes and safety induction.', order: 2 },
      { id: 'it_lt3', time: '10:00 AM', activity: 'Heavy Machine Shop Tour', description: '5-axis CNC machines and robotic welding systems.', order: 3 },
      { id: 'it_lt4', time: '12:30 PM', activity: 'Non-Destructive Testing Lab', description: 'Ultrasonic and dye-penetrant testing demonstrations.', order: 4 },
      { id: 'it_lt5', time: '01:30 PM', activity: 'Lunch at L&T Officers Mess', description: 'Buffet lunch for students and faculty.', order: 5 },
      { id: 'it_lt6', time: '02:30 PM', activity: 'Aerospace & Defense Wing Briefing', description: 'Precision tooling for launch vehicles and defense systems.', order: 6 },
      { id: 'it_lt7', time: '04:00 PM', activity: 'Q&A & Certificate Distribution', description: 'Conclusion of visit and return bus departure.', order: 7 },
    ],
    travelInfo: {
      reportingTime: '08:00 AM',
      reportingLocation: 'VIT Main Gate — Bus Bay #3',
      departureTime: '08:30 AM',
      transport: 'University AC Coach (Vehicle No: MH-01-VIT-303)',
      expectedArrival: '09:15 AM',
      returnDeparture: '04:30 PM',
      campusArrival: '05:30 PM',
    },
    requirements: ['VIT Student ID Card', 'Boarding Pass QR Code', 'Closed footwear'],
    rules: ['Follow safety instructions of shop-floor escorts at all times'],
  },

  {
    id: 'exp_infosys_06',
    title: 'Infosys Autonomous Systems & Software Engineering Experience',
    organization: 'Infosys Limited',
    organizationDescription: 'Global leader in next-generation digital services and consulting with world-renowned innovation labs.',
    organizationIndustry: 'Enterprise Software & Cloud Platforms',
    organizationWebsite: 'https://www.infosys.com',
    organizationLogo: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=120&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
    experienceType: 'Technical Tours',
    shortDescription: 'Exploring autonomous AI agents, enterprise DevOps pipelines, and digital experience studios.',
    detailedDescription: 'Spend a full immersion day at the Infosys Pune Development Center. Experience interactive demonstrations of enterprise autonomous agents, AI-assisted code refactoring, and modern agile project delivery.',
    date: '2026-10-28',
    location: 'Infosys Pune Development Center, Hinjawadi Phase 2, Pune',
    address: 'Plot No. 24, Rajiv Gandhi Infotech Park, Hinjawadi Phase 2, Pune, Maharashtra 411057',
    contribution: 300,
    capacity: 50,
    waitlistEnabled: true,
    waitlistCapacity: 20,
    registrationOpen: '2026-08-25T00:00:00Z',
    registrationDeadline: '2026-10-20T23:59:59Z',
    status: 'PUBLISHED',
    createdBy: 'usr_faculty_1',
    primaryFacultyId: 'usr_faculty_1',
    createdAt: '2026-08-25T10:00:00Z',
    updatedAt: '2026-08-27T12:00:00Z',
    eligibility: {
      allowedBranches: ['Computer Science & Engineering', 'Information Technology', 'Electronics & Communication Engineering'],
      allowedYears: [2, 3, 4],
      allowedSemesters: [3, 4, 5, 6, 7, 8],
      allowedDivisions: ['A', 'B', 'C', 'D'],
      minCgpa: 6.5,
    },
    whatYouWillLearn: [
      'Enterprise generative AI agents for automated software delivery and code synthesis',
      'Microservices observability and distributed tracing at scale',
      'Campus hiring pathways, InfyTQ certification benefits, and internship tracks',
    ],
    learningObjectives: [
      'Evaluate full-lifecycle enterprise agile development frameworks',
      'Understand API-first architectures and distributed caching strategies',
    ],
    experienceHighlights: [
      { icon: 'Code', title: 'Topaz AI Studio', description: 'Live coding session demonstrating AI agent assisted debugging.' },
      { icon: 'Building2', title: 'Smart Campus Tour', description: 'Walkthrough of green architectural marvels and collaborative tech zones.' },
      { icon: 'Award', title: 'InfyTQ Career Session', description: 'Guidance on HackWithInfy hackathon prep and high-package interview tracks.' },
    ],
    whyAttend: [
      'Direct connection with senior delivery managers and campus recruiting executives',
      'Learn modern software engineering industry standards beyond college syllabi',
      'Tour one of India’s premier sustainable corporate tech parks',
    ],
    safetyInfo: {
      dressCode: 'Business casual attire (collared shirts, jeans/chinos, smart footwear).',
      requiredGear: 'Visitor badges will be issued at the main security building.',
      importantRules: ['Photography restricted to designated campus selfie zones'],
    },
    companyInfo: {
      website: 'https://www.infosys.com',
      about: 'Infosys is a global leader in next-generation digital services and consulting, enabling clients in more than 56 countries to navigate their digital transformation.',
      employees: '315,000+ Globally',
      headquarters: 'Bengaluru / Development Centers across Pune, Chennai, Hyderabad, Mumbai',
    },
    itinerary: [
      { id: 'it_infy1', time: '06:30 AM', activity: 'Departure from VIT', description: 'Highway coach departure for Hinjawadi, Pune.', order: 1 },
      { id: 'it_infy2', time: '10:00 AM', activity: 'Arrival & Welcome Session', description: 'Check-in and opening address by Principal Consultant.', order: 2 },
      { id: 'it_infy3', time: '11:00 AM', activity: 'Infosys Topaz AI & Cloud Showcase', description: 'Interactive demo of AI engineering workflows.', order: 3 },
      { id: 'it_infy4', time: '01:00 PM', activity: 'Lunch at Infosys Food Court', description: 'Executive buffet luncheon.', order: 4 },
      { id: 'it_infy5', time: '02:00 PM', activity: 'Digital Studio & UX Lab', description: 'Interactive human-centered design and VR testing lab.', order: 5 },
      { id: 'it_infy6', time: '03:30 PM', activity: 'HackWithInfy Career Masterclass', description: 'Problem-solving strategies and interview prep.', order: 6 },
      { id: 'it_infy7', time: '05:00 PM', activity: 'Return Transit', description: 'Bus leaves for Mumbai; arrival at VIT by 08:30 PM.', order: 7 },
    ],
    travelInfo: {
      reportingTime: '06:15 AM',
      reportingLocation: 'VIT Main Gate — Bus Bay #2',
      departureTime: '06:30 AM',
      transport: 'University AC Deluxe Coach (Vehicle No: MH-01-VIT-505)',
      expectedArrival: '10:00 AM',
      returnDeparture: '05:00 PM',
      campusArrival: '08:30 PM',
    },
    requirements: ['VIT Student ID Card', 'Boarding Pass QR Code', 'Govt ID Proof'],
    rules: ['Adhere strictly to corporate campus escort guidelines'],
  },

  {
    id: 'exp_mahindra_07',
    title: 'Mahindra & Mahindra EV Powertrain & Crash Safety Testing Center',
    organization: 'Mahindra & Mahindra',
    organizationDescription: 'Leading automotive and farm equipment giant leading Indias SUV market and developing cutting-edge EV platforms.',
    organizationIndustry: 'Automobile & EV Engineering',
    organizationWebsite: 'https://www.mahindra.com',
    organizationLogo: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=120&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800&auto=format&fit=crop&q=80',
    experienceType: 'Industrial Visits',
    shortDescription: 'Observing crash test simulation rigs, electric motor dyno calibration, and climatic wind tunnel testing.',
    detailedDescription: 'Step inside Mahindra Research Valley and Chakan Plant testing facilities. Learn how SUVs and Born Electric EV platforms undergo 5-star Bharat NCAP crash safety testing, NVH acoustic analysis, and extreme climatic endurance trials.',
    date: '2026-11-05',
    location: 'Mahindra Plant & Research Center, Chakan Phase II, Pune',
    address: 'Plot No. A-1, Phase II, MIDC Chakan Industrial Area, Pune, Maharashtra 410501',
    contribution: 550,
    capacity: 32,
    waitlistEnabled: true,
    waitlistCapacity: 15,
    registrationOpen: '2026-09-01T00:00:00Z',
    registrationDeadline: '2026-10-28T23:59:59Z',
    status: 'PUBLISHED',
    createdBy: 'usr_faculty_2',
    primaryFacultyId: 'usr_faculty_2',
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-02T12:00:00Z',
    eligibility: {
      allowedBranches: ['Mechanical Engineering', 'Electronics & Communication Engineering', 'Electrical & Electronics Engineering'],
      allowedYears: [2, 3, 4],
      allowedSemesters: [4, 5, 6, 7, 8],
      allowedDivisions: ['A', 'B'],
      minCgpa: 6.8,
    },
    whatYouWillLearn: [
      'Crashworthiness evaluation protocols under Bharat NCAP & Global NCAP',
      'Electric drivetrain torque vectoring and motor control algorithms',
      'Noise, Vibration & Harshness (NVH) acoustic chamber measurements',
    ],
    learningObjectives: [
      'Understand automotive crash test telemetry and high-speed photogrammetry',
      'Analyze finite element analysis (FEA) validation against real crash data',
    ],
    experienceHighlights: [
      { icon: 'ShieldAlert', title: 'Crash Safety Arena', description: 'Overview of impact barrier rigs and instrumented anthropomorphic test devices (dummies).' },
      { icon: 'Volume2', title: 'Semi-Anechoic NVH Chamber', description: 'Acoustic measurement of motor whine and structural vibrations.' },
      { icon: 'Zap', title: 'High-Voltage Dyno Lab', description: 'Electric motor endurance and regenerative braking testing.' },
    ],
    whyAttend: [
      'Witness state-of-the-art automotive testing infrastructure rare in academic settings',
      'Direct bridge between mechanics of materials and vehicle safety engineering',
      'Interaction with Chief Testing Engineers',
    ],
    safetyInfo: {
      dressCode: 'Heavy trousers, collared shirt, and safety shoes.',
      requiredGear: 'Protective goggles and ear protection provided before entry to testing bays.',
      importantRules: ['Do not cross test track barriers during vehicle dynamic passes'],
    },
    companyInfo: {
      website: 'https://www.mahindra.com',
      about: 'Mahindra & Mahindra is an Indian multinational automotive manufacturing corporation headquartered in Mumbai, leading Indias SUV and EV revolution.',
      employees: '260,000+ Globally across Mahindra Group',
      headquarters: 'Mumbai, Maharashtra, India',
    },
    itinerary: [
      { id: 'it_mm1', time: '06:00 AM', activity: 'VIT Gate Assembly & Departure', description: 'Intercity AC transit coach leaves for Chakan, Pune.', order: 1 },
      { id: 'it_mm2', time: '09:45 AM', activity: 'Plant Reception & Safety Induction', description: 'Safety briefing and pass verification.', order: 2 },
      { id: 'it_mm3', time: '10:30 AM', activity: 'Crash Test & Structural Safety Facility', description: 'Walkthrough of impact rigs and high-speed camera setups.', order: 3 },
      { id: 'it_mm4', time: '12:30 PM', activity: 'Semi-Anechoic NVH Acoustic Lab', description: 'Demonstration of acoustic soundproofing and sensor rigs.', order: 4 },
      { id: 'it_mm5', time: '01:30 PM', activity: 'Lunch at Executive Mess', description: 'Complimentary buffet lunch.', order: 5 },
      { id: 'it_mm6', time: '02:30 PM', activity: 'EV Powertrain Dynamometer Labs', description: 'Live motor torque testing and thermal imaging.', order: 6 },
      { id: 'it_mm7', time: '04:00 PM', activity: 'Automotive Engineering Q&A', description: 'Discussion with Vehicle Dynamics leads.', order: 7 },
      { id: 'it_mm8', time: '05:00 PM', activity: 'Return to Mumbai', description: 'Arrival back at VIT Campus around 08:30 PM.', order: 8 },
    ],
    travelInfo: {
      reportingTime: '05:45 AM',
      reportingLocation: 'VIT Main Gate — Bus Bay #1',
      departureTime: '06:00 AM',
      transport: 'University Inter-City Coach (Vehicle No: MH-01-VIT-808)',
      expectedArrival: '09:45 AM',
      returnDeparture: '05:00 PM',
      campusArrival: '08:30 PM',
    },
    requirements: ['VIT Student ID Card', 'Boarding Pass QR', 'Closed footwear'],
    rules: ['Safety instructions must be obeyed in active testing bays'],
  },

  {
    id: 'exp_bosch_08',
    title: 'Bosch ADAS Radar & Embedded Automotive Electronics Center',
    organization: 'Bosch India',
    organizationDescription: 'Leading global supplier of technology and services in mobility solutions, industrial technology, and consumer goods.',
    organizationIndustry: 'Automotive Electronics & Embedded Systems',
    organizationWebsite: 'https://www.bosch.in',
    organizationLogo: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=120&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=800&auto=format&fit=crop&q=80',
    experienceType: 'Technical Tours',
    shortDescription: 'Hands-on look at 77GHz automotive millimeter-wave radar, camera sensor fusion, and AUTOSAR software stacks.',
    detailedDescription: 'Visit the Bosch Technical Center to observe how autonomous driving algorithms fuse radar, LiDAR, and camera streams. Explore hardware-in-the-loop (HIL) simulators and AUTOSAR adaptive embedded software architectures.',
    date: '2026-11-12',
    location: 'Bosch Technical Center, Adugodi / Electronic City, Bengaluru',
    address: 'Hosur Road, Adugodi, Bengaluru, Karnataka 560030',
    contribution: 600,
    capacity: 28,
    waitlistEnabled: true,
    waitlistCapacity: 12,
    registrationOpen: '2026-09-05T00:00:00Z',
    registrationDeadline: '2026-11-02T23:59:59Z',
    status: 'PUBLISHED',
    createdBy: 'usr_faculty_1',
    primaryFacultyId: 'usr_faculty_1',
    createdAt: '2026-09-05T11:00:00Z',
    updatedAt: '2026-09-08T12:00:00Z',
    eligibility: {
      allowedBranches: ['Electronics & Communication Engineering', 'Computer Science & Engineering', 'Electrical & Electronics Engineering'],
      allowedYears: [3, 4],
      allowedSemesters: [5, 6, 7, 8],
      allowedDivisions: ['A', 'B', 'C'],
      minCgpa: 7.5,
    },
    whatYouWillLearn: [
      'Automotive millimeter-wave radar signal processing (FMCW chirps & FFT velocity resolution)',
      'Hardware-in-the-Loop (HIL) simulation testbenches for ABS and ESP controllers',
      'AUTOSAR Adaptive Platform architectures and ISO 26262 functional safety (ASIL-D)',
    ],
    learningObjectives: [
      'Evaluate sensor fusion algorithms for emergency autonomous braking (AEB)',
      'Understand CAN-FD, FlexRay, and Automotive Ethernet communication protocols',
    ],
    experienceHighlights: [
      { icon: 'Radio', title: 'Radar Anechoic Chamber', description: 'RF beamforming and cross-section characterization demo.' },
      { icon: 'Cpu', title: 'Hardware-in-the-Loop Rig', description: 'Simulated vehicle driving testbench triggering ECU reactions in real-time.' },
      { icon: 'ShieldCheck', title: 'Functional Safety Briefing', description: 'Principles of zero-defect automotive software engineering.' },
    ],
    whyAttend: [
      'Bosch is the undisputed world benchmark in automotive electronics and ADAS systems',
      'Essential exposure for embedded systems, DSP, and autonomous robotics aspirants',
      'Information on Bosch India graduate engineering trainee intakes',
    ],
    safetyInfo: {
      dressCode: 'Formal academic attire with closed leather footwear.',
      requiredGear: 'Anti-static wristbands and ESD lab coats provided in cleanroom testing suites.',
      importantRules: ['No magnets or high-frequency transmitters near calibration chambers'],
    },
    companyInfo: {
      website: 'https://www.bosch.in',
      about: 'Bosch in India is a leading supplier of technology and services in the areas of Mobility Solutions, Industrial Technology, Consumer Goods, and Energy and Building Technology.',
      employees: '38,000+ in India (over 30,000 in R&D and Software)',
      headquarters: 'Bengaluru, Karnataka, India',
    },
    itinerary: [
      { id: 'it_b1', time: '08:00 AM', activity: 'Reporting & Campus Check-in', description: 'Security gate passes and orientation.', order: 1 },
      { id: 'it_b2', time: '09:30 AM', activity: 'Keynote on ADAS & Autonomous Mobility', description: 'Presentation by Chief Engineer, Mobility Solutions.', order: 2 },
      { id: 'it_b3', time: '11:00 AM', activity: 'RF Radar & Sensor Fusion Suite', description: 'Demonstration of 77GHz FMCW radar and optical camera fusion.', order: 3 },
      { id: 'it_b4', time: '01:00 PM', activity: 'Buffet Lunch at Bosch Club House', description: 'Hosted lunch for students and faculty.', order: 4 },
      { id: 'it_b5', time: '02:00 PM', activity: 'Hardware-in-the-Loop Simulation Lab', description: 'Live fault-injection testing on automotive braking ECUs.', order: 5 },
      { id: 'it_b6', time: '03:45 PM', activity: 'Career Pathways & Internship Q&A', description: 'Interactive breakout with Bosch HR and Technical Leads.', order: 6 },
      { id: 'it_b7', time: '05:00 PM', activity: 'Conclusion & Departure', description: 'Wrap-up and transfer.', order: 7 },
    ],
    travelInfo: {
      reportingTime: '07:30 AM',
      reportingLocation: 'VIT Main Gate',
      departureTime: '08:00 AM',
      transport: 'University Special Transit',
      expectedArrival: '09:00 AM',
      returnDeparture: '05:00 PM',
      campusArrival: '06:30 PM',
    },
    requirements: ['VIT Student ID Card', 'Boarding Pass QR', 'Govt ID Proof'],
    rules: ['Non-disclosure agreement must be respected in lab zones'],
  },

  {
    id: 'exp_adani_09',
    title: 'Adani Automated Container Terminal & Green Hydrogen Hub',
    organization: 'Adani Ports and Special Economic Zone',
    organizationDescription: 'Indias largest commercial port operator and integrated logistics provider pioneering automated maritime cargo systems.',
    organizationIndustry: 'Ports, Logistics & Renewable Energy',
    organizationWebsite: 'https://www.adaniports.com',
    organizationLogo: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=120&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&auto=format&fit=crop&q=80',
    experienceType: 'Industrial Visits',
    shortDescription: 'Tour of automated quay cranes (STS), automated guided vehicles (AGVs), and smart port logistics operations.',
    detailedDescription: 'Visit the automated marine terminal to observe optical character recognition container tracking, computerized crane scheduling, and clean green hydrogen fuel cell pilot facilities.',
    date: '2026-11-20',
    location: 'Adani Terminal & Logistics Hub, JNPT Port Corridor, Navi Mumbai',
    address: 'Sheva, Navi Mumbai Industrial Port Zone, Maharashtra 400707',
    contribution: 350,
    capacity: 35,
    waitlistEnabled: true,
    waitlistCapacity: 15,
    registrationOpen: '2026-09-10T00:00:00Z',
    registrationDeadline: '2026-11-10T23:59:59Z',
    status: 'PUBLISHED',
    createdBy: 'usr_faculty_2',
    primaryFacultyId: 'usr_faculty_2',
    createdAt: '2026-09-10T10:00:00Z',
    updatedAt: '2026-09-12T12:00:00Z',
    eligibility: {
      allowedBranches: ['Civil Engineering', 'Mechanical Engineering', 'Electrical & Electronics Engineering', 'Computer Science & Engineering'],
      allowedYears: [2, 3, 4],
      allowedSemesters: [3, 4, 5, 6, 7, 8],
      allowedDivisions: ['A', 'B'],
      minCgpa: 6.5,
    },
    whatYouWillLearn: [
      'Automated container terminal logistics and optical crane positioning systems',
      'Port maritime civil infrastructure, breakwater design, and berth construction',
      'Green hydrogen electrolyzer integration and zero-emission port transport',
    ],
    learningObjectives: [
      'Understand SCADA integration for large-scale maritime material handling',
      'Analyze supply chain optimization algorithms for intermodal rail-road freight',
    ],
    experienceHighlights: [
      { icon: 'Ship', title: 'Automated Quay Crane Berth', description: 'Observe remote crane operators controlling massive gantry lifts via video telemetry.' },
      { icon: 'Truck', title: 'AGV Container Routing', description: 'Automated electric terminal trucks navigating container yards autonomously.' },
      { icon: 'Sun', title: 'Renewable Power Substation', description: 'Solar and wind hybrid microgrid powering port utilities.' },
    ],
    whyAttend: [
      'Witness the sheer physical scale of international maritime commerce and logistics automation',
      'Relevant for civil, mechanical, electrical, and systems optimization engineering',
      'Comprehensive port safety certification upon completion',
    ],
    safetyInfo: {
      dressCode: 'Full trousers, long-sleeve shirts, and sturdy footwear. No open sandals permitted.',
      requiredGear: 'High-visibility safety vests, hard hats, and steel-toe shoe caps issued at terminal gate.',
      importantRules: ['Stay within designated safety viewing zones away from crane movement paths'],
    },
    companyInfo: {
      website: 'https://www.adaniports.com',
      about: 'Adani Ports and Special Economic Zone Limited (APSEZ) is India’s largest private port operator and an end-to-end logistics solutions provider.',
      employees: '30,000+ Direct and Indirect Personnel',
      headquarters: 'Ahmedabad, Gujarat / Terminal operations in Navi Mumbai',
    },
    itinerary: [
      { id: 'it_ad1', time: '07:30 AM', activity: 'VIT Bus Assembly', description: 'Identity verification and bus departure.', order: 1 },
      { id: 'it_ad2', time: '09:00 AM', activity: 'Port Security Gate Check-in', description: 'Biometric pass clearance and mandatory safety video.', order: 2 },
      { id: 'it_ad3', time: '10:00 AM', activity: 'Terminal Operations Center (TOC)', description: 'Computerized berth allocation and vessel planning systems.', order: 3 },
      { id: 'it_ad4', time: '11:45 AM', activity: 'Wharf & Container Berth Inspection', description: 'Live observation of Ship-to-Shore (STS) gantry cranes in action.', order: 4 },
      { id: 'it_ad5', time: '01:15 PM', activity: 'Lunch at Port Officers Club', description: 'Complimentary executive meal.', order: 5 },
      { id: 'it_ad6', time: '02:15 PM', activity: 'Green Hydrogen Hub & Rail Yard Tour', description: 'Clean energy fueling and automated rail loading.', order: 6 },
      { id: 'it_ad7', time: '03:45 PM', activity: 'Logistics Tech Q&A', description: 'Interactive discussion with Terminal Operations VP.', order: 7 },
      { id: 'it_ad8', time: '04:45 PM', activity: 'Return Transit', description: 'Return to VIT Campus by 06:15 PM.', order: 8 },
    ],
    travelInfo: {
      reportingTime: '07:15 AM',
      reportingLocation: 'VIT Main Gate — Bus Bay #3',
      departureTime: '07:30 AM',
      transport: 'University AC Coach (Vehicle No: MH-01-VIT-606)',
      expectedArrival: '09:00 AM',
      returnDeparture: '04:45 PM',
      campusArrival: '06:15 PM',
    },
    requirements: ['VIT ID Card', 'Govt Photo ID (Mandatory for Port Entry)', 'Boarding Pass QR'],
    rules: ['Port security regulations are strictly enforced'],
  },

  {
    id: 'exp_isro_10',
    title: 'ISRO Satellite Application Centre & Telemetry Ground Station',
    organization: 'Indian Space Research Organisation (ISRO)',
    organizationDescription: 'Indias premier national space agency executing deep space missions, satellite navigation (NavIC), and earth observation.',
    organizationIndustry: 'Aerospace & Space Technology',
    organizationWebsite: 'https://www.isro.gov.in',
    organizationLogo: 'https://images.unsplash.com/photo-1517976487507-5b3b4b45f942?w=120&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80',
    experienceType: 'Field Research',
    shortDescription: 'Exclusive tour of deep space telemetry ground stations, satellite integration cleanrooms, and thermal-vacuum test chambers.',
    detailedDescription: 'Students experienced a specialized immersion at ISTRAC tracking facilities and payload assembly suites, learning about orbital tracking algorithms, satellite telecommanding, and space-grade electronic hardening.',
    date: '2026-07-20',
    location: 'ISTRAC Spacecraft Control Centre, Peenya Industrial Area, Bengaluru',
    address: 'Plot No. 12 & 13, Peenya Industrial Area 3rd Phase, Bengaluru, Karnataka 560058',
    contribution: 0,
    capacity: 30,
    waitlistEnabled: true,
    waitlistCapacity: 15,
    registrationOpen: '2026-06-15T00:00:00Z',
    registrationDeadline: '2026-07-10T23:59:59Z',
    status: 'COMPLETED',
    createdBy: 'usr_faculty_1',
    primaryFacultyId: 'usr_faculty_1',
    createdAt: '2026-06-15T08:00:00Z',
    updatedAt: '2026-07-21T18:00:00Z',
    eligibility: {
      allowedBranches: ['Computer Science & Engineering', 'Electronics & Communication Engineering', 'Information Technology'],
      allowedYears: [3, 4],
      allowedSemesters: [6, 7, 8],
      allowedDivisions: ['A', 'B'],
      minCgpa: 8.0,
    },
    whatYouWillLearn: [
      'Deep space telemetry reception, modulation schemes, and error-correcting codes',
      'Cleanroom electrostatic discharge (ESD) and satellite vibration testing standards',
      'Orbital trajectory propagation and real-time antenna tracking telemetry',
    ],
    learningObjectives: [
      'Understand spacecraft telemetry architectures and telecommand authentication',
      'Analyze space radiation hardening techniques for microelectronics',
    ],
    experienceHighlights: [
      { icon: 'Satellite', title: 'Mission Operations Complex (MOX)', description: 'Observation of live deep space tracking antennas and telemetry screens.' },
      { icon: 'Radio', title: 'Deep Space Network Antenna', description: 'Technical walkthrough of 32-meter cryogenic dish antenna.' },
      { icon: 'Award', title: 'Space Scientist Keynote', description: 'Address on Chandrayaan and Gaganyaan avionics architectures.' },
    ],
    whyAttend: [
      'Prestigious national laboratory visit with highest institutional security clearance',
      'Completed past milestone with verified digital certificates issued to attendees',
      'Exceptional career inspiration in aerospace and telecommunications engineering',
    ],
    safetyInfo: {
      dressCode: 'Strictly formal institutional attire.',
      requiredGear: 'Special security clearance visitor badges and ESD cleanroom protective overalls.',
      importantRules: ['Mobile phones and electronic media strictly deposited at security gate'],
    },
    companyInfo: {
      website: 'https://www.isro.gov.in',
      about: 'The Indian Space Research Organisation is the national space agency of India, operating under the Department of Space, headquartered in Bengaluru.',
      employees: '17,000+ Scientists, Engineers, and Staff',
      headquarters: 'Antariksh Bhavan, Bengaluru, Karnataka, India',
    },
    itinerary: [
      { id: 'it_isro1', time: '06:00 AM', activity: 'Departure', description: 'Early morning campus transit.', order: 1 },
      { id: 'it_isro2', time: '09:00 AM', activity: 'ISTRAC Mission Control Tour', description: 'Observation of live tracking antennas.', order: 2 },
      { id: 'it_isro3', time: '11:30 AM', activity: 'Payload Cleanroom Gallery', description: 'Satellite integration viewing.', order: 3 },
      { id: 'it_isro4', time: '01:00 PM', activity: 'Lunch at ISRO Canteen', description: 'Official hosted meal.', order: 4 },
      { id: 'it_isro5', time: '02:00 PM', activity: 'Space Avionics Lecture', description: 'Interaction with senior ISRO flight dynamics scientists.', order: 5 },
      { id: 'it_isro6', time: '03:30 PM', activity: 'Return Transit', description: 'Departure back to university.', order: 6 },
    ],
    travelInfo: {
      reportingTime: '05:30 AM',
      reportingLocation: 'VIT Main Gate',
      departureTime: '06:00 AM',
      transport: 'University Transit',
      expectedArrival: '09:00 AM',
      returnDeparture: '03:30 PM',
      campusArrival: '06:30 PM',
    },
    requirements: ['VIT ID Card', 'Special Security Clearance Pass', 'Aadhaar Card'],
    rules: ['No mobile phones permitted past security checkpoint'],
  },

  {
    id: 'exp_godrej_11',
    title: 'Godrej Aerospace Precision Tooling & Smart Factory Tour',
    organization: 'Godrej & Boyce Aerospace Wing',
    organizationDescription: 'Pioneering precision manufacturing company supplying cryogenic rocket engines, aerospace thrusters, and satellite components.',
    organizationIndustry: 'Aerospace & Precision Manufacturing',
    organizationWebsite: 'https://www.godrej.com',
    organizationLogo: 'https://images.unsplash.com/photo-1581092334651-ddf26d9a09d0?w=120&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1581092162384-8987c1d64718?w=800&auto=format&fit=crop&q=80',
    experienceType: 'Industrial Visits',
    shortDescription: 'Observing precision electron-beam welding, cryogenic engine injector machining, and automated smart warehousing.',
    detailedDescription: 'Godrej Aerospace opens its high-tech manufacturing bays in Vikhroli. Witness electron-beam welding in high-vacuum chambers, aerospace titanium milling, and automated guided vehicles in smart warehousing.',
    date: '2026-11-26',
    location: 'Pirojshanagar Industrial Complex, Vikhroli East, Mumbai',
    address: 'Eastern Express Highway, Vikhroli East, Mumbai, Maharashtra 400079',
    contribution: 250,
    capacity: 25,
    waitlistEnabled: true,
    waitlistCapacity: 10,
    registrationOpen: '2026-09-15T00:00:00Z',
    registrationDeadline: '2026-11-18T23:59:59Z',
    status: 'PUBLISHED',
    createdBy: 'usr_faculty_2',
    primaryFacultyId: 'usr_faculty_2',
    createdAt: '2026-09-15T10:00:00Z',
    updatedAt: '2026-09-18T12:00:00Z',
    eligibility: {
      allowedBranches: ['Mechanical Engineering', 'Electronics & Communication Engineering', 'Electrical & Electronics Engineering'],
      allowedYears: [2, 3, 4],
      allowedSemesters: [3, 4, 5, 6, 7, 8],
      allowedDivisions: ['A', 'B'],
      minCgpa: 7.0,
    },
    whatYouWillLearn: [
      'Electron-beam welding and vacuum brazing for aerospace cryogenic liquid engines',
      'Precision coordinate measuring machines (CMM) achieving sub-micron verification',
      'Automated high-bay warehouse logistics and automated material replenishment',
    ],
    learningObjectives: [
      'Analyze metallurgy of superalloys (Inconel, Titanium, Monel) under extreme thermal stresses',
      'Evaluate advanced CNC toolpath generation for complex rocket nozzle contours',
    ],
    experienceHighlights: [
      { icon: 'Flame', title: 'Electron Beam Welding Suite', description: 'Watch high-energy electron beam joining thick-walled aerospace alloys in high vacuum.' },
      { icon: 'Compass', title: 'Precision Metrology Lab', description: 'Laser interferometry and coordinate measuring machine demonstrations.' },
      { icon: 'Box', title: 'Smart Automated Warehouse', description: 'Robotic automated storage and retrieval system (ASRS) in live operation.' },
    ],
    whyAttend: [
      'Convenient central Mumbai location with short transit time',
      'Hands-on look at rocket engine manufacturing that powers Indian satellite launches',
      'Interaction with Chief Manufacturing Technologists',
    ],
    safetyInfo: {
      dressCode: 'Clean formal trousers and collared shirt with sturdy closed footwear.',
      requiredGear: 'Safety glasses and ESD heel straps provided for metrology lab entry.',
      importantRules: ['Keep hands away from vacuum chamber seals and optical sensors'],
    },
    companyInfo: {
      website: 'https://www.godrej.com',
      about: 'Godrej & Boyce Aerospace manufactures mission-critical precision components for aerospace, defense, and space exploration missions.',
      employees: '15,000+ Across Godrej & Boyce',
      headquarters: 'Pirojshanagar, Vikhroli, Mumbai, India',
    },
    itinerary: [
      { id: 'it_god1', time: '08:30 AM', activity: 'VIT Gate Departure', description: 'Short transit via Eastern Express Highway.', order: 1 },
      { id: 'it_god2', time: '09:15 AM', activity: 'Pirojshanagar Check-in', description: 'Visitor badge distribution and company history video.', order: 2 },
      { id: 'it_god3', time: '10:00 AM', activity: 'Cryogenic Engine Component Bay', description: 'Machining of rocket engine injector heads and liquid fuel pumps.', order: 3 },
      { id: 'it_god4', time: '11:45 AM', activity: 'Electron Beam Welding & Vacuum Brazing', description: 'Demonstration of deep-penetration weld joints.', order: 4 },
      { id: 'it_god5', time: '01:00 PM', activity: 'Lunch at Godrej Executive Mess', description: 'Buffet lunch hosted for attendees.', order: 5 },
      { id: 'it_god6', time: '02:00 PM', activity: 'Smart Warehousing & ASRS Robotics', description: 'Automated retrieval systems and AGVs.', order: 6 },
      { id: 'it_god7', time: '03:30 PM', activity: 'Q&A on Aerospace Engineering', description: 'Session with Aerospace General Manager.', order: 7 },
      { id: 'it_god8', time: '04:30 PM', activity: 'Return to VIT', description: 'Arrival back at campus by 05:15 PM.', order: 8 },
    ],
    travelInfo: {
      reportingTime: '08:15 AM',
      reportingLocation: 'VIT Main Gate — Bus Bay #2',
      departureTime: '08:30 AM',
      transport: 'University AC Bus (Vehicle No: MH-01-VIT-101)',
      expectedArrival: '09:15 AM',
      returnDeparture: '04:30 PM',
      campusArrival: '05:15 PM',
    },
    requirements: ['VIT Student ID Card', 'Boarding Pass QR', 'Closed footwear'],
    rules: ['Follow instructions inside high-vacuum clean zones'],
  },

  {
    id: 'exp_bhel_12',
    title: 'BHEL High-Voltage Transmission & Electrical Machinery Labs',
    organization: 'Bharat Heavy Electricals Limited (BHEL)',
    organizationDescription: 'Indias largest power generation equipment manufacturer and engineering enterprise powering the national electrical grid.',
    organizationIndustry: 'Power Systems & High-Voltage Equipment',
    organizationWebsite: 'https://www.bhel.com',
    organizationLogo: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=120&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=800&auto=format&fit=crop&q=80',
    experienceType: 'Industrial Visits',
    shortDescription: 'Observing ultra-high voltage (UHV) transformer testing, steam turbine rotor dynamic balancing, and switchgear manufacturing.',
    detailedDescription: 'Tour BHEL major manufacturing plant to observe 765kV extra-high voltage transformer windings, impulse lightning generator tests, and multi-megawatt synchronous generator stator assembly.',
    date: '2026-12-04',
    location: 'BHEL Heavy Electricals Plant, Piplani, Bhopal',
    address: 'Piplani, Habibganj, Bhopal, Madhya Pradesh 462022',
    contribution: 500,
    capacity: 30,
    waitlistEnabled: true,
    waitlistCapacity: 15,
    registrationOpen: '2026-09-20T00:00:00Z',
    registrationDeadline: '2026-11-25T23:59:59Z',
    status: 'PUBLISHED',
    createdBy: 'usr_faculty_2',
    primaryFacultyId: 'usr_faculty_2',
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-22T12:00:00Z',
    eligibility: {
      allowedBranches: ['Electrical & Electronics Engineering', 'Mechanical Engineering', 'Electronics & Communication Engineering'],
      allowedYears: [2, 3, 4],
      allowedSemesters: [4, 5, 6, 7, 8],
      allowedDivisions: ['A', 'B'],
      minCgpa: 6.8,
    },
    whatYouWillLearn: [
      'Ultra-high voltage (765kV/1200kV) transformer core and winding assembly techniques',
      'Impulse voltage testing replicating lightning strikes on transmission equipment',
      'Hydro & steam turbine rotor balancing and dynamic vibration testing',
    ],
    learningObjectives: [
      'Understand dielectric breakdown, corona discharge mitigation, and SF6 gas switchgear',
      'Analyze power transmission grid stability under high renewable energy penetration',
    ],
    experienceHighlights: [
      { icon: 'Zap', title: 'Extra High Voltage Testing Bay', description: 'Live demonstration of high-voltage arc breakdown and dielectric insulation checks.' },
      { icon: 'Cog', title: 'Turbine Rotor Balancing Bay', description: 'Massive multi-ton generator rotors dynamically spun and balanced.' },
      { icon: 'Shield', title: 'Grid Protection Relay Suite', description: 'Numerical relays and SCADA automation for regional grid substations.' },
    ],
    whyAttend: [
      'Indispensable exposure for electrical and power systems engineering disciplines',
      'Understand how national grid transmission infrastructure is engineered and tested',
      'Direct guidance on GATE PSU recruitment and BHEL engineer trainee profiles',
    ],
    safetyInfo: {
      dressCode: 'Heavy cotton pants and shirts. Rubber sole footwear mandatory for electrical safety.',
      requiredGear: 'Safety helmets and high-voltage warning zone badges provided at gate.',
      importantRules: ['Maintain safe distance from high-voltage clearance fencing'],
    },
    companyInfo: {
      website: 'https://www.bhel.com',
      about: 'Bharat Heavy Electricals Limited is an Indian public sector engineering and manufacturing enterprise, owned by the Government of India, Ministry of Heavy Industries.',
      employees: '30,000+ Nationwide',
      headquarters: 'New Delhi, India / Manufacturing plants in Bhopal, Haridwar, Trichy, Hyderabad',
    },
    itinerary: [
      { id: 'it_bh1', time: '08:00 AM', activity: 'Plant Arrival & Security Clearance', description: 'Gate pass issuance and safety video.', order: 1 },
      { id: 'it_bh2', time: '09:15 AM', activity: 'Transformer & Reactor Block', description: 'High-voltage transformer assembly and oil filtration.', order: 2 },
      { id: 'it_bh3', time: '11:30 AM', activity: 'High Voltage Testing Laboratory', description: 'Impulse voltage lightning surge simulation test.', order: 3 },
      { id: 'it_bh4', time: '01:00 PM', activity: 'Lunch at BHEL Officers Club', description: 'Hosted lunch for students and faculty.', order: 4 },
      { id: 'it_bh5', time: '02:00 PM', activity: 'Turbine & Heavy Rotating Machine Block', description: 'Dynamic balancing and stator winding insertion.', order: 5 },
      { id: 'it_bh6', time: '03:45 PM', activity: 'PSU Career Pathways Discussion', description: 'Interaction with BHEL Senior Technical Directors.', order: 6 },
      { id: 'it_bh7', time: '05:00 PM', activity: 'Departure', description: 'Conclusion of visit.', order: 7 },
    ],
    travelInfo: {
      reportingTime: '07:30 AM',
      reportingLocation: 'Designated Transit Bay',
      departureTime: '08:00 AM',
      transport: 'Special Institutional Transit Coach',
      expectedArrival: '09:00 AM',
      returnDeparture: '05:00 PM',
      campusArrival: '06:30 PM',
    },
    requirements: ['VIT Student ID Card', 'Boarding Pass QR Code', 'Rubber-soled footwear'],
    rules: ['Respect high voltage clearance boundaries at all times'],
  },

  {
    id: 'exp_drdo_13',
    title: 'DRDO Advanced Armament & Defense Systems R&D Wing',
    organization: 'Defence Research and Development Organisation (DRDO)',
    organizationDescription: 'Indias premier military research agency developing state-of-the-art autonomous weapons, radars, combat vehicles, and missile avionics.',
    organizationIndustry: 'Defense Technology & Autonomous Systems',
    organizationWebsite: 'https://www.drdo.gov.in',
    organizationLogo: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=120&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?w=800&auto=format&fit=crop&q=80',
    experienceType: 'Field Research',
    shortDescription: 'Exclusive tour of armament design laboratories, ballistics testing tunnels, and autonomous combat robotics.',
    detailedDescription: 'Step inside the Armament Research & Development Establishment (ARDE) complex. Discover how defense scientists design ballistic projectiles, multi-spectral sensors, and autonomous drone swarm telemetry.',
    date: '2026-12-10',
    location: 'ARDE Complex, Dr. Homi Bhabha Road, Pashan, Pune',
    address: 'Dr. Homi Bhabha Road, Pashan, Pune, Maharashtra 411021',
    contribution: 0,
    capacity: 24,
    waitlistEnabled: true,
    waitlistCapacity: 12,
    registrationOpen: '2026-09-25T00:00:00Z',
    registrationDeadline: '2026-12-01T23:59:59Z',
    status: 'PUBLISHED',
    createdBy: 'usr_faculty_1',
    primaryFacultyId: 'usr_faculty_1',
    createdAt: '2026-09-25T10:00:00Z',
    updatedAt: '2026-09-28T12:00:00Z',
    eligibility: {
      allowedBranches: ['Computer Science & Engineering', 'Electronics & Communication Engineering', 'Mechanical Engineering'],
      allowedYears: [3, 4],
      allowedSemesters: [5, 6, 7, 8],
      allowedDivisions: ['A', 'B'],
      minCgpa: 7.8,
      additionalRules: 'Strict background verification and Indian citizenship mandatory for defense establishment clearance.',
    },
    whatYouWillLearn: [
      'Ballistics telemetry, internal pressure curve modeling, and warhead dynamics',
      'Autonomous drone swarming algorithms and anti-jamming communication protocols',
      'Hardened embedded computing architectures resistant to electromagnetic pulse (EMP)',
    ],
    learningObjectives: [
      'Evaluate military-grade MIL-STD-810 environmental testing protocols',
      'Understand embedded real-time operating systems (RTOS) in guidance computers',
    ],
    experienceHighlights: [
      { icon: 'Shield', title: 'Ballistics Tunnel & High-Speed Imaging', description: 'Observe ultra-high-speed 1,000,000 fps cameras capturing projectile aerodynamics.' },
      { icon: 'Bot', title: 'Combat Robotics Lab', description: 'Demonstration of autonomous tracked reconnaissance rovers.' },
      { icon: 'Award', title: 'Defense Scientist Interactive Forum', description: 'Career pathways in DRDO Scientist-B recruitment and research fellowships.' },
    ],
    whyAttend: [
      '100% capacity filled with active waiting list demonstrating peak student demand',
      'Ultra-exclusive defense research establishment entry for selected students',
      'Zero fee contribution funded by institutional research grant',
    ],
    safetyInfo: {
      dressCode: 'Formal university uniform / collared attire with physical ID badge.',
      requiredGear: 'Special defense security credentials issued at check-post.',
      importantRules: ['No electronic smart devices or smartwatches allowed past Main Gate security'],
    },
    companyInfo: {
      website: 'https://www.drdo.gov.in',
      about: 'The Defence Research and Development Organisation is the premier agency under the Ministry of Defence, dedicated to achieving self-reliance in critical defense technologies.',
      employees: '30,000+ Personnel (over 5,000 active Scientists)',
      headquarters: 'DRDO Bhawan, New Delhi / Laboratories nationwide including Pune, Bengaluru, Hyderabad',
    },
    itinerary: [
      { id: 'it_dr1', time: '06:00 AM', activity: 'Departure from VIT Gate', description: 'Highway coach transit to Pune.', order: 1 },
      { id: 'it_dr2', time: '09:30 AM', activity: 'Security Protocol & Verification', description: 'Identity check, credential verification, and mobile deposit.', order: 2 },
      { id: 'it_dr3', time: '10:15 AM', activity: 'ARDE Museum & Heritage Gallery', description: 'Walkthrough of indigenous armament breakthroughs.', order: 3 },
      { id: 'it_dr4', time: '11:30 AM', activity: 'Ballistics & Aerodynamics Facility', description: 'High-speed camera imaging and projectile simulation.', order: 4 },
      { id: 'it_dr5', time: '01:00 PM', activity: 'Lunch at Officers Mess', description: 'Hosted lunch for students and faculty.', order: 5 },
      { id: 'it_dr6', time: '02:00 PM', activity: 'Autonomous Robotics & Telemetry Suite', description: 'Unmanned ground vehicles and sensor fusion demo.', order: 6 },
      { id: 'it_dr7', time: '03:45 PM', activity: 'Interactive Session with Scientist-G Director', description: 'Q&A on self-reliance in defense technologies.', order: 7 },
      { id: 'it_dr8', time: '04:45 PM', activity: 'Return Transit', description: 'Arrival at VIT Campus by 08:30 PM.', order: 8 },
    ],
    travelInfo: {
      reportingTime: '05:45 AM',
      reportingLocation: 'VIT Main Gate — Bus Bay #1',
      departureTime: '06:00 AM',
      transport: 'University Inter-City Coach (Vehicle No: MH-01-VIT-707)',
      expectedArrival: '09:30 AM',
      returnDeparture: '04:45 PM',
      campusArrival: '08:30 PM',
    },
    requirements: ['Physical VIT Student ID Card', 'Original Aadhaar Card (Mandatory)', 'Boarding Pass QR'],
    rules: ['Strict adherence to defense establishment security guidelines'],
  },

  {
    id: 'exp_barc_14',
    title: 'BARC Nuclear Instrumentation & Radiation Safety Complex',
    organization: 'Bhabha Atomic Research Centre (BARC)',
    organizationDescription: 'Indias premier multi-disciplinary nuclear research facility executing research in reactor physics, medical isotopes, and instrumentation.',
    organizationIndustry: 'Nuclear Engineering & Instrumentation',
    organizationWebsite: 'https://www.barc.gov.in',
    organizationLogo: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=120&auto=format&fit=crop&q=80',
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    experienceType: 'Field Research',
    shortDescription: 'Tour of research reactor control room simulations, medical isotope synthesis, and radiation monitoring instrument suites.',
    detailedDescription: 'Visit the Bhabha Atomic Research Centre complex in Trombay, Mumbai. Discover precision neutron flux instrumentation, SCADA safety interlocks for nuclear reactors, and healthcare radioisotope manufacturing pipelines.',
    date: '2026-12-18',
    location: 'BARC Complex, Trombay, Mumbai',
    address: 'Trombay, Mumbai, Maharashtra 400085',
    contribution: 0,
    capacity: 25,
    waitlistEnabled: true,
    waitlistCapacity: 10,
    registrationOpen: '2026-10-01T00:00:00Z',
    registrationDeadline: '2026-12-08T23:59:59Z',
    status: 'PUBLISHED',
    createdBy: 'usr_faculty_1',
    primaryFacultyId: 'usr_faculty_1',
    createdAt: '2026-10-01T10:00:00Z',
    updatedAt: '2026-10-05T12:00:00Z',
    eligibility: {
      allowedBranches: ['Biomedical Engineering', 'Electronics & Communication Engineering', 'Computer Science & Engineering', 'Electrical & Electronics Engineering'],
      allowedYears: [2, 3, 4],
      allowedSemesters: [4, 5, 6, 7, 8],
      allowedDivisions: ['A', 'B'],
      minCgpa: 7.5,
      additionalRules: 'Indian nationality verified via Aadhaar card required for Department of Atomic Energy (DAE) visitor gate pass.',
    },
    whatYouWillLearn: [
      'Nuclear reactor control rod instrumentation and fail-safe hardware interlocks',
      'Radiation detection using scintillation detectors, Geiger-Müller counters, and semiconductor sensors',
      'Medical radioisotope synthesis and automated radiopharmaceutical cleanrooms',
    ],
    learningObjectives: [
      'Understand triple-redundant instrumentation and safety systems (SIL-4)',
      'Analyze digital signal processing in nuclear pulse spectroscopy',
    ],
    experienceHighlights: [
      { icon: 'Radio', title: 'Reactor Control Simulator', description: 'Full-scale interactive simulation console of Dhruva research reactor.' },
      { icon: 'Activity', title: 'Health Physics & Radiation Suite', description: 'Radiation dosimeter calibration and shielding physics demonstration.' },
      { icon: 'HeartPulse', title: 'Medical Radiopharmacy Lab', description: 'Production of Technetium-99m and therapeutic cancer isotopes.' },
    ],
    whyAttend: [
      'Rare opportunity to enter Indias founding nuclear research institution',
      'Direct relevance for biomedical, electronics, instrumentation, and computing students',
      'Fully funded educational exposure visit with zero fee',
    ],
    safetyInfo: {
      dressCode: 'Formal university collared attire and closed footwear.',
      requiredGear: 'Personal radiation dosimeter badges and shoe covers provided at Health Physics counter.',
      importantRules: ['Dosimeters must be worn on outer garment at all times'],
    },
    companyInfo: {
      website: 'https://www.barc.gov.in',
      about: 'Bhabha Atomic Research Centre is Indias premier nuclear research facility, headquartered in Trombay, Mumbai, Maharashtra, founded by Dr. Homi J. Bhabha in 1954.',
      employees: '14,000+ Scientists, Engineers, and Technical Personnel',
      headquarters: 'Trombay, Mumbai, Maharashtra, India',
    },
    itinerary: [
      { id: 'it_barc1', time: '08:00 AM', activity: 'VIT Gate Assembly & Transit', description: 'Bus departure for Trombay.', order: 1 },
      { id: 'it_barc2', time: '08:45 AM', activity: 'North Gate Security Badging', description: 'Identity verification and dosimeter issuance.', order: 2 },
      { id: 'it_barc3', time: '09:30 AM', activity: 'Central Complex Auditorium Briefing', description: 'Welcome address on peaceful uses of atomic energy.', order: 3 },
      { id: 'it_barc4', time: '10:45 AM', activity: 'Reactor Control Simulation Facility', description: 'Interactive demonstration of reactor instrumentation consoles.', order: 4 },
      { id: 'it_barc5', time: '12:30 PM', activity: 'Lunch at BARC Officers Club', description: 'Hosted lunch for attendees.', order: 5 },
      { id: 'it_barc6', time: '01:30 PM', activity: 'Medical Isotopes & Radiation Instrumentation', description: 'Tour of scintillation spectrometry and radiation safety suites.', order: 6 },
      { id: 'it_barc7', time: '03:30 PM', activity: 'Interactive Session with Senior DAE Scientists', description: 'BARC Training School (OCES/DGFS) recruitment pathways.', order: 7 },
      { id: 'it_barc8', time: '04:30 PM', activity: 'Return Transit', description: 'Arrival back at VIT Campus by 05:30 PM.', order: 8 },
    ],
    travelInfo: {
      reportingTime: '07:45 AM',
      reportingLocation: 'VIT Main Gate — Bus Bay #1',
      departureTime: '08:00 AM',
      transport: 'University AC Coach (Vehicle No: MH-01-VIT-102)',
      expectedArrival: '08:45 AM',
      returnDeparture: '04:30 PM',
      campusArrival: '05:30 PM',
    },
    requirements: ['Physical VIT Student ID Card', 'Original Aadhaar Card (Mandatory for DAE Gate)', 'Boarding Pass QR'],
    rules: ['Adhere strictly to Health Physics radiation safety guidelines'],
  },
];
